// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: sync.proto

package sync_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncV1_GetObjectList_FullMethodName = "/sync_v1.SyncV1/GetObjectList"
)

// SyncV1Client is the client API for SyncV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncV1Client interface {
	GetObjectList(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type syncV1Client struct {
	cc grpc.ClientConnInterface
}

func NewSyncV1Client(cc grpc.ClientConnInterface) SyncV1Client {
	return &syncV1Client{cc}
}

func (c *syncV1Client) GetObjectList(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, SyncV1_GetObjectList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncV1Server is the server API for SyncV1 service.
// All implementations must embed UnimplementedSyncV1Server
// for forward compatibility.
type SyncV1Server interface {
	GetObjectList(context.Context, *SyncRequest) (*SyncResponse, error)
	mustEmbedUnimplementedSyncV1Server()
}

// UnimplementedSyncV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncV1Server struct{}

func (UnimplementedSyncV1Server) GetObjectList(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObjectList not implemented")
}
func (UnimplementedSyncV1Server) mustEmbedUnimplementedSyncV1Server() {}
func (UnimplementedSyncV1Server) testEmbeddedByValue()                {}

// UnsafeSyncV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncV1Server will
// result in compilation errors.
type UnsafeSyncV1Server interface {
	mustEmbedUnimplementedSyncV1Server()
}

func RegisterSyncV1Server(s grpc.ServiceRegistrar, srv SyncV1Server) {
	// If the following call pancis, it indicates UnimplementedSyncV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncV1_ServiceDesc, srv)
}

func _SyncV1_GetObjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncV1Server).GetObjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncV1_GetObjectList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncV1Server).GetObjectList(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncV1_ServiceDesc is the grpc.ServiceDesc for SyncV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync_v1.SyncV1",
	HandlerType: (*SyncV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetObjectList",
			Handler:    _SyncV1_GetObjectList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync.proto",
}
